# Generated by Django 5.1.3 on 2024-11-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpPosition',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('perm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('config_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('config_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.empposition')),
            ],
        ),
        migrations.CreateModel(
            name='EmpWorkHourLeave',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateTimeField()),
                ('leave_duration', models.IntegerField()),
                ('leave_type', models.IntegerField()),
                ('leave_desc', models.CharField(max_length=400)),
                ('is_salary', models.IntegerField()),
                ('status', models.IntegerField()),
                ('approver', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpGivenSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.IntegerField()),
                ('salary_year', models.IntegerField()),
                ('given_amount', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'salary_month', 'salary_year'), name='unique_emp_given_salary')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department_id', 'emp_id'), name='unique_department_head')],
            },
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('salary_desc', models.CharField(max_length=400)),
                ('salary_amount', models.IntegerField()),
                ('active_from', models.DateField()),
                ('inactiv_since', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'salary_type', 'status'), name='unique_emp_salary')],
            },
        ),
        migrations.CreateModel(
            name='EmpSalaryCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('sum_hour', models.IntegerField()),
                ('salaray_hour', models.IntegerField()),
                ('hourly_salary', models.IntegerField()),
                ('salary_sum', models.IntegerField()),
                ('ndsh_tax', models.IntegerField()),
                ('hhot_tax', models.IntegerField()),
                ('status', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'work_date'), name='unique_emp_salary_calc')],
            },
        ),
        migrations.CreateModel(
            name='EmpWorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('work_start_date', models.DateTimeField()),
                ('work_end_date', models.DateTimeField()),
                ('salary_hour', models.IntegerField()),
                ('late_hour', models.IntegerField()),
                ('leave_hour', models.IntegerField()),
                ('status', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'work_date'), name='unique_emp_work_hour')],
            },
        ),
        migrations.CreateModel(
            name='EmpPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('perm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.permission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'perm_id'), name='unique_emp_perm')],
            },
        ),
    ]
