# Generated by Django 5.1.3 on 2024-12-05 01:19

from django.db import migrations

def populate_table(apps, schema_editor):
    SalaryConfig = apps.get_model('payroll', 'SalaryConfig')
    SalaryConfig.objects.bulk_create([SalaryConfig(config_name="NDSH", config_value = "15"), SalaryConfig(config_name="HHOT", config_value = "5")])

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employee_birth_date'),
    ]

    operations = [
        migrations.RunPython(populate_table)
    ]
